/* Copyright (c) IAIK, Graz University of Technology, 2015.
 * All rights reserved.
 * Contact: http://opensource.iaik.tugraz.at
 * 
 * This file is part of the Secure Block Device Library.
 * 
 * Commercial License Usage
 * Licensees holding valid commercial licenses may use this file in
 * accordance with the commercial license agreement provided with the
 * Software or, alternatively, in accordance with the terms contained in
 * a written agreement between you and SIC. For further information
 * contact us at http://opensource.iaik.tugraz.at.
 * 
 * Alternatively, this file may be used under the terms of the GNU General
 * Public License as published by the Free Software Foundation version 2.
 * 
 * The Secure Block Device Library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with the Secure Block Device Library. If not, see <http://www.gnu.org/licenses/>.
 */
///
/// \file
/// \brief Specifies a Secure Block Device Library cryptographic abstraction
/// layer using no cryptography whatsoever.
///
/// This cryptographic abstraction layer is intended for testing and debugging
/// the Secure Block Device Library. It does not provide any form of protection
/// for the actual data.
///
#ifdef __cplusplus
extern "C" {
#endif

#ifndef SBDI_NOCRYPTO_H_
#define SBDI_NOCRYPTO_H_

#include "sbdi_crypto.h"

/*!
 * \brief Creates a new SBDI cryptographic abstraction layer that does not
 * actually perform any cryptography
 *
 * This Cryptography Abstraction Layer generated by this function implements
 * the encryption and decryption as NOP. This means the encryption will
 * return a simple copy of the plaintext, and an empty tag consisting of
 * solely zeros.
 *
 * @param crypto[out] a pointer pointer to the newly created cryptography
 * abstraction layer
 * @param key[in] the key to use for the cryptography abstraction layer; can be
 * NULL as it will be ignored.
 * @return SBDI_SUCCESS if the operation succeeds;
 */
sbdi_error_t sbdi_nocrypto_create(sbdi_crypto_t **crypto, const sbdi_key_t key);

/*!
 * \brief Destroys the given SBDI cryptographic abstraction layer
 *
 * Warning: Only use this function for cryptographic abstraction layers
 * created with the sbdi_nocrypto_create function!
 *
 * @param crypto[in] the cryptographic abstraction layer to destroy
 */
void sbdi_nocrypto_destroy(sbdi_crypto_t *crypto);

#endif /* SBDI_NOCRYPTO_H_ */

#ifdef __cplusplus
}
#endif
